### PR TITLE
changes to pom.xml to include jsf-core 2.3 dependency

### PR DESCRIPTION
**Pull request by shrinubabu**
Able to build and run the application on internal tomcat after including jsf-core 2.3 dependency to pom

### CODE REVIEW

**Review by rohitvvv — CHANGES_REQUESTED** [review]
The latest snapshot of 2.3 changes are available here https://maven.java.net/content/repositories/snapshots/org/glassfish/javax.faces/
Also perhaps the only we you can consume 2.3 is by consuming the jar and maven-install-plugin. 
You can find an example here 
https://github.com/rohitvvv/JSF2.3/blob/master/pom.xml

**Comment by shrinubabu** [comment]
I see that its not required. As I have observed the jsf-core-2.3.jar is also being copied to WEB-INF/lib without including maven-install-plugin. And build is running fine. Please issue command "mvn clean install tomcat:run" using the pom.xml and verify.

**Comment by shrinubabu** [comment]
i have copied the jsf 2.3 dependency from the JSF2.3 scaffold project created by you

**Review by rohitvvv — APPROVED** [review]

**Review by rohitvvv — CHANGES_REQUESTED** [review]
I still don't see the new changes in this review.

**Comment by shrinubabu** [comment]
will create a new pull request with suggested changes

**Pull request closed without merging**
